### ISSUE TITLE
Non-usage des variables d'environnement pour le client

### ISSUE THREAD

**Issue by UP-4303** [XadosIV/UrbanPark_ProjetS4#13]
Les variables d'environnement ne sont pas utilisées sur la partie client. Les variables d'environnement actuellement définis sont :
* `PORT` : Port du serveur
* `DATABASE` Nom de la base de donnée
* `USER` Utilisateur MySQL
* `PASSWORD` Mot de passe MySQL
* `HOST` Domaine MySQL

Exemple : 
Pour l'accès à l'API, le client utilise systématiquement le port `3001`. Cependant, `3001` est le port du server par défaut mais `process.env.PORT` devrait être utilisé en priorité si défini.

**Comment by Poutchy** [comment]
juste pour être sur, qu'est ce que je dois répondre à cela?
tu voudrais que je modifie quelque chose?
je suis d'accord avec ce que tu viens d'écrire certes, c'est ma foie malin et bien défini
mais pourquoi m'avoir assigner?
peux tu indiquer précisément ce que tu veux que je fasse de cette information?
si tu le souhaite, je peux ajouter un truc pour des variables d'environnement pour le client, mais avec le peux que je viens de lire, j'avoue que je ne vois pas ce que tu veux dire....

**Comment by Poutchy** [comment]
je vais essayer d'en faire un avant minuit et je finirais demain matin s'il le faut

**Comment by Poutchy** [comment]
question:
est ce que ces variables sont les même que celle qui sont dans le fichier du serveur?
si oui, est ce que le mieux serait pas de faire un .env commun aux 2, ou l'on met tous les appels, et qu'on stocke hors des 2 dossiers?

**Comment by Poutchy** [comment]
> 

auquel cas, je n'aurais qu'à changer le .env du serveur en le remontant d'un dossier et lui donner le port d'écoute

**Comment by UP-4303** [comment]
Je te l'ai assigné parce que tu es le plus gros contributeur du front.
L'exemple donné semble indiquer ce que je voudrais pour ce cas assez clairement.
Peut être ajouter une variable pour le port de react ?
À toi de voir si tu as d'autres idées, tu connais ton code mieux que moi

**Comment by Poutchy** [comment]
> Je te l'ai assigné parce que tu es le plus gros contributeur du front. L'exemple donné semble indiquer ce que je voudrais pour ce cas assez clairement. Peut être ajouter une variable pour le port de react ? À toi de voir si tu as d'autres idées, tu connais ton code mieux que moi

alors justement
c'est plus que totalement possible: c'est la solution dont je parlais au dessus
tu peux, en effet, mettre des variables d'environnement pour (par exemple) les numéros de ports, les adresses de liens, et autres liens
mais ce que je me pose comme question c'est "est ce qu eles différentes infos entre le serv et le client sont pas les même (host, name, port, etc) et si oui, ne devrions on nous pas aller les prendre du coup au  même endroit?
mais faut que je vérifie si les variables d'env peuvent pas déjà se fair epasser comme ça, auquel cas il suffira de les appeler sans changer un fichier de place
enfin, oui, il est aussi possible de créer ces info avec le port réact comme tu le dis mais je crois que, ce faisant, tu dois le passer à tous tes composants, et si c'est ça ,c'est pas super ouf

**Comment by Poutchy** [comment]
heure oblige, j'appliquerai tous mes dires demain matin
bonsoir à tous

**Comment by Poutchy** [comment]
Suites au différentes remarques et recherches, nous avons pu remarquer que le principe d'un .env partagé est une mauvaise idée.
Nous faisons donc le choix d'avoir un .env par dossier (un pour le client et un pour le serveur).
Choix validé par l'équipe.
